resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: bitroid
      path: hemanth22/jfrogpipelinelearning
      branches:
        include: master
  - name: DockerAppImage
    type: Image
    configuration:
      registry: JFROG
      sourceRepository: bitroidDocker
      imageName: docker.artifactory/swampup_docker_app_demo
      imageTag: '${run_number}'
      autoPull: true
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: JFROG
      buildName: SampleApp
      buildNumber: 1
pipelines:
  - name: swampup_docker_app_pipeline
    configuration:
      environmentVariables:
        readOnly:
           my_env_var: '1.0.$run_number'
           ArtIP: $(echo ${int_ArtifactoryUnified_url}|awk -F '/' '{print $3}'|awk -F ':' '{print $1}')
