resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      gitProvider: bitroid
      path: hemanth22/jfrogpipelinelearning
      branches:
        include: master
  - name: DockerAppImage
    type: Image
    configuration:
      registry: JFROG
      sourceRepository: bitroidDocker
      imageName: docker.artifactory/swampup_docker_app_demo
      imageTag: '${run_number}'
      autoPull: true
  - name: myBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: JFROG
      buildName: SampleApp
      buildNumber: 1
pipelines:
  - name: swampup_docker_app_pipeline
    configuration:
      environmentVariables:
        readOnly:
           my_env_var: '1.0.$run_number'
           ArtIP: $(echo ${int_ArtifactoryUnified_url}|awk -F '/' '{print $3}'|awk -F ':' '{print $1}')
    steps:
      - name: bld_docker_app
        type: DockerBuild
        configuration:
          affinityGroup: fmkGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: docker.${ArtIP}/swampup_docker_app_demo
          dockerImageTag: '${run_number}'
          integrations:
            - name: bitroidDocker
          inputResources:
            - name: myGitRepo
              trigger: false
          outputResources:
            - name: DockerAppImage
          inputSteps:
            - name: bld_backend
            - name: publish_frontend #bld_frontend
        execution:
          onStart:
            - sed -i "s/docker.artifactory/docker.${ArtIP}/" $res_myGitRepo_resourcePath/Dockerfile
            - sed -i "s/frontend-3.0.0/frontend-$previous_frontend_ver/g" $res_myGitRepo_resourcePath/Dockerfile
            - sed -i "s/1.0.0/$previous_backend_ver/g" $res_myGitRepo_resourcePath/Dockerfile
          onComplete:
            - echo $step_env_var2
            - echo "Running $pipeline_name | $step_name on node ID $step_node_id"
